<?php

namespace AppBundle\Repository;

/**
 * InLogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InLogEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
