<?php

namespace AppBundle\Repository;

/**
 * InNavEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InNavEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
