security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        main:
            pattern:      ^/
            form_login:
                provider:       fos_userbundle
                csrf_token_generator : security.csrf.token_manager
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                default_target_path: /
                always_use_default_target_path: true
                # success_handler: valeo.main.login_success_handler
                remember_me: true
            switch_user: true
            logout:
                path:   /logout
                target: /
            security: true
            anonymous: true
            remember_me:
                secret:      "%secret%"
                lifetime: 86400 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                remember_me_parameter: _remember_me
                always_remember_me: true
            switch_user: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    role_hierarchy:
        #ROLE_USER: [IS_AUTHENTICATED_ANONYMOUSLY]
        ROLE_PERSONNAGE: [ROLE_USER,ROLE_PERSONNAGE_SHOW]
        ROLE_ADMIN_RARETE: [ROLE_USER,ROLE_ADMIN_RARETE_LIST,ROLE_ADMIN_RARETE_SHOW,ROLE_ADMIN_RARETE_EDIT,ROLE_ADMIN_RARETE_DEL]
        ROLE_ADMIN_PERSONNAGE: [ROLE_USER,ROLE_ADMIN_PERSONNAGE_LIST,ROLE_ADMIN_PERSONNAGE_SHOW,ROLE_ADMIN_PERSONNAGE_EDIT,ROLE_ADMIN_PERSONNAGE_DEL]
        ROLE_ADMIN:       [ROLE_USER,ROLE_ADMIN_RARETE,ROLE_ADMIN_PERSONNAGE,ROLE_PERSONNAGE]
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
